module:
  mounts:
    - source: assets
      target: assets
    - source: content
      target: content
    - source: data
      target: data
    - source: layouts
      target: layouts
    - source: static
      target: static

languages:
  fr:
    permalinks:
      expertises: /expertises/:slug/
      persons: /equipe/:slug/
      persons_expertises: /equipe/expertises/:slug/
      persons_places: /equipe/cabinets/:slug/
      persons_statutes: /equipe/status/:slug/
      places: /cabinet/:slug/
      posts: /actualite/:year-:month-:day-:slug/
      postss_categories: /actualite/categories/:slug/
      publications: /parutions/:year-:slug/
      publications_categories: /parutions/categories/:slug/
      publications_expertises: /parutions/expertises/:slug/
      publications_persons: /parutions/avocats/:slug/
  en:
    permalinks:
      expertises: /expertises/:slug/
      persons: /team/:slug/
      persons_expertises: /team/expertises/:slug/
      persons_places: /team/firms/:slug/
      persons_statutes: /team/status/:slug/
      places: /firm/:slug/
      posts: /news/:year-:month-:day-:slug/
      postss_categories: /news/categories/:slug/
      publications: /publications/:year-:slug/
      publications_categories: /publications/categories/:slug/
      publications_expertises: /publications/expertises/:slug/
      publications_persons: /publications/lawyers/:slug/

params:
  _merge: deep
  persons:
    _merge: deep
    thumbnail:
      _merge: deep
      desktop: "306x372"
      mobile: "300x365"
  posts:
    _merge: deep
    thumbnail:
      _merge: deep
      desktop: "636x420"
  places:
    _merge: deep
    items:
      _merge: deep
      large: false
